version: '3.1'
services:
  db:
    container_name: postgres
    image: postgres:15.2
    environment:
      POSTGRES_USER: amigoscode
      POSTGRES_PASSWORD: password
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - db
    restart: unless-stopped
#  pgadmin:
#    container_name: pgadmin
#    image: dpage/pgadmin4
#    environment:
#      PGADMIN_DEFAULT_EMAIL: amigoscode@gmail.com
#      PGADMIN_DEFAULT_PASSWORD: password
#      PGADMIN_CONFIG_SERVER_MODE: 'False'
#    volumes:
#      - pgadmin:/var/lib/pgadmin
#    ports:
#      - "5050:80"
#    networks:
#      - db
#    restart: unless-stopped
#    depends_on:
#      - db
  amigoscode-api:
    container_name: amigoscode-api
    image: cmingfai/full-stack-professional
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
        - "8088:8080"
    networks:
        - db
    restart: unless-stopped
    depends_on:
        - db

  amigoscode-react:
    container_name: amigoscode-react
    image: cmingfai/amigoscode-react
    build:
        context: frontend/react
    ports:
        - "3000:5173"
    depends_on:
        - amigoscode-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  postgres:
  pgadmin: